"""add doctor_id and medication_schedules

Revision ID: 730b285bdd33
Revises: f353e2a1d8c7
Create Date: 2026-07-03 15:51:03.718784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730b285bdd33'
down_revision: Union[str, None] = 'f353e2a1d8c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('medicine_name', sa.String(length=150), nullable=False),
    sa.Column('dosage', sa.String(length=60), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=False),
    sa.Column('first_dose_time', sa.String(length=5), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_schedules_patient_id'), 'medication_schedules', ['patient_id'], unique=False)
    op.add_column('users', sa.Column('doctor_id', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('specialty', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('hospital', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_users_doctor_id'), 'users', ['doctor_id'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['doctor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_doctor_id'), table_name='users')
    op.drop_column('users', 'hospital')
    op.drop_column('users', 'specialty')
    op.drop_column('users', 'doctor_id')
    op.drop_index(op.f('ix_medication_schedules_patient_id'), table_name='medication_schedules')
    op.drop_table('medication_schedules')
    # ### end Alembic commands ###